### ISSUE TITLE
Add Leia Organa page 

### ISSUE THREAD

**Issue by aflussing** [aflussing/swapi-playandfun#4]
1. Add a link to the page of Leia as done with Darth Vader in the **index.html**
2. Create **leia-organa.html** file.
3. **Copy** the html/js **code** from **darth-vader.html** and paste it to **leia-organa.html**.
4.  Change the url where it consumes the API to the Leia object. 
Example"https://swapi.co/api/people/4" (Darth Vader) to  "https://swapi.co/api/people/5" (Leia)

**Comment by danigz6** [comment]
Can I take this issue?
