### ISSUE TITLE
Add Obi-Wan Kenobi page

### ISSUE THREAD

**Issue by aflussing** [aflussing/swapi-playandfun#5]
1. Add a **link** to the page of **Obi-Wan Kenobi** as done with Darth Vader in the **index.html**
2. Create **obi-wan-kenobi.html** file.
3. **Copy** the html/js **code** from **darth-vader.html** file.
4.  Change the url where it consumes the API to the Obi-Wan object. 
Example"https://swapi.co/api/people/4" (Darth Vader) to  "https://swapi.co/api/people/10" (Obi-Wan)

**Comment by danigz6** [comment]
Can I take this issue?
